#!/bin/bash

# Usage function to print to stderr
usage() {
  echo "Usage: $(basename $0) directory_name" >&2
  exit 1
}

if [ $# -eq 0 ]; then
  echo "Error: No directory name provided." >&2
  usage # Print usage and exit
fi

directory_name="$1"

echo "creating $directory_name..."
mkdir -p "$directory_name"
cd "$directory_name"

# create directories for libraries and assets
echo "creating libraries and assets directories..."
mkdir -p "libraries"
mkdir -p "assets"

# create main.lua file
echo "creating main.lua and appending default love2d functions..."
touch "main.lua"
echo "function love.load() end" >> main.lua
echo "function love.update(dt) end" >> main.lua
echo "function love.draw() end" >> main.lua

# create .editorconfig file
echo "creating editorconfig and setting options..."
touch ".editorconfig"
echo "[*.lua]" >> .editorconfig
echo "indent_style = space" >> .editorconfig
echo "indent_size = 2" >> .editorconfig
echo "trim_trailing_whitespace = true" >> .editorconfig

echo "completed!"
